# Generated by Django 2.2.1 on 2019-05-22 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
