# Generated by Django 2.2.1 on 2019-05-25 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolshare', '0003_tool_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=250)),
                ('bike_type', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('model_pic', models.CharField(max_length=250)),
                ('guide_pic', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('available', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
