# Generated by Django 2.2.1 on 2019-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolshare', '0004_auto_20190525_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='available',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Not Available')], default=True),
        ),
    ]
